FROM python:3.10-slim
ENV PYTHONUNBUFFERED=1

RUN apt-get update \
 && apt-get install -y --no-install-recommends netcat-openbsd dos2unix \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY scripts/ ./scripts/

RUN dos2unix ./scripts/wait-for-kafka-and-spark.sh \
 && chmod +x ./scripts/wait-for-kafka-and-spark.sh \
 && chmod +x ./scripts/*.py

